New game SDK
emortalmc/java-game-sdk pull request #2
Opened 2023-07-02 19:04 UTC by BomBardyGamer

Here's the PR for the new game SDK changes that I've made. I'll highlight some important changes below to make it easier to review.

### Initialisation and entry points for game servers

The entire way stuff is initialised has been completely redone.

Previously, the `GameSdkModule` would be statically initialised by a module from the game server, which was okay, but very messy, especially since we definitely didn't need static initialisation, and this way of having the game server create its own module and register it as part of the system was unnecessary boilerplate that had to be present in every game server.

In the new version, the game SDK initialisation is no longer part of the module system, and is done separately, which means the game servers only have to create the server and provide the game SDK config, which they would normally have to do with the old system anyway. This is much cleaner, and means less boilerplate on the game servers.

### Game removal

Game removal is now very different.

The way it used to work is that when the game was finished, it would call in to the game manager directly, which was a bit messy, but wasn't that bad when things were done with static initialisation. However, with the new system, it would mean passing the game manager in to every game instance, or doing some messy static initialisation, which was an option I did not want to take.  
Providing the game manager to the games would mean every game would need to have an extra parameter that they would need to accept in and pass to the super constructor, which is extra boilerplate for the game servers again.  
Having the game manager be a singleton seems like an okay option, but the game manager relies on the config, so it would mean a lateinit singleton that is initialised somewhere, which is very messy, and was not an option I even considered. It is only now, on review, that I see this option as a possibility.

In the new version, what I decided to do instead was use events. Using events means that not only do I not need to pass in the game manager to the games, but the games do not need to have any awareness of the game manager's existence at all, which means that the job that the game SDK does is completely transparent to the game servers. There are some concerns to be made over performance, but it is very unlikely that this will cause a significant performance degradation.

In addition to this, the previously duplicated logic for finishing, which was for the game servers to send all the players back to the lobby and kick them if they were not sent back, is now something the game manager handles. The games now have a `cleanUp` method as part of their API, to allow the games to clean up anything game-specific that the game servers have, after the players have been removed.

This way of doing things will also mean that things like requeueing games could be done entirely within the game manager, with the game only needing to indicate to the game manager that players have requested a requeue, after which the game manager can move the players to a fresh, new game, instead of kicking them. I know @ZakShearman said about making this seamless, but I think that this would likely be the better way, as recreating the game means less duplicated logic in the game, and also ensures that the game will be in the same starting state that players would expect when they requeue.

### Game lifecycle

The `onPlayerLogin` method has been renamed to `onJoin`, taking a `Player` instead of the player login event. The solution here required that every game provide an instance for the game SDK to set the spawning instance to, but as every game does this anyway, and every game will most definitely require some sort of instance for players to be able to play the game, I don't see this as a bad thing.

There is also now an `onLeave` method, which is called when the disconnect event is sent. This allows the game to handle player disconnections, without knowing exactly how they work, which allows us to simulate this behaviour if desired for testing purposes. It also means that every game doesn't need to individually listen to the disconnect event.

## Stuff that still needs reviewing

#### GameCountUpdatedEvent

The `GameCountUpdatedEvent` was added to allow `AgonesGameHandler` to be disconnected from the game manager. However, having an event and firing it for the entire event stack just for this very small, very specific functionality seems like a bad idea. I don't really want the should allocate logic to be inside the game manager, as I'd like it to be agnostic as to whether it's running in a testing or production environment. Perhaps I could create a listener interface and pass that in to the game manager.

2023-07-06 19:09 UTC, ZakShearman requested changes

2023-07-06 19:09 UTC, ZakShearman commented on src/main/java/dev/emortal/minestom/gamesdk/internal/listener/AgonesGameUpdateListener.java
> +    private int gameCount;
Maybe make an AtomicInteger?

Maybe I'm being a bit pedantic as technically this is completely fine right now it's just so decoupled a change to how Kafka messages are processed (e.g. in a thread pool) or multiple kafka consumers if necessary could break this.

2023-07-06 19:47 UTC, BomBardyGamer commented on build.gradle.kts
> +    api("dev.emortal.minestom:core:ec7fd44") // should be provided by any user
Yeah this is a difficult one. I still don't fully know what we should do about library updates.

An automated rollout is most definitely a bad idea, as there may be breaking API changes, and it's also a much larger scale than just a single server updating. If we made an update that was broken and it automatically rolled out, for example in the Minestom core, it could bring down all the servers on the network, which would cause big issues.

However, having to manually update the core everywhere it's used every time we update it is really annoying, and would only get more annoying with more game servers.

We'll have to have a discussion about this some time.

2023-07-06 19:49 UTC, BomBardyGamer commented on src/main/java/dev/emortal/minestom/gamesdk/internal/GameManager.java
> +                    Thread.sleep(1000);
Yeah this was mostly a temporary fix to a kinda dumb problem. Perhaps we could put players in a queue and process them when we're sure the game they're going in to is ready, or something like that.

This is another one that we need to have a discussion about.

2023-07-06 19:51 UTC, BomBardyGamer commented on src/main/java/dev/emortal/minestom/gamesdk/internal/GameManager.java
> +            while (this.games.isEmpty()) {
The problem here was on the first load of games. The thing is, because of how the matchmaker works, we can't be sure that players won't be sent to the game while it is still under construction. What was happening before is that this logic would get processed before the game would be created, and the player would be stuck in a broken state because they wouldn't match any of the existing servers, and wouldn't get sent to any of them.

2023-07-06 19:54 UTC, BomBardyGamer commented on src/main/java/dev/emortal/minestom/gamesdk/internal/GameManager.java
> +        });
Yeah this was sort of covered by my comment on the one above. This issue is exactly what the hacky while loop is designed to prevent.

With the while loop in place, this case will never happen where no game is found, as we wait until games are available. However, this is a bad solution to this problem, as it could block stuff for other games.

2023-07-06 19:55 UTC, BomBardyGamer commented on build.gradle.kts
> +    mavenLocal()
I left it in because a lot of the other repositories have maven local in their repositories list. Maybe I should've spotted this as a bug rather than just following what the others were doing.

2023-07-06 19:56 UTC, BomBardyGamer commented on src/main/java/dev/emortal/minestom/gamesdk/config/GameSdkConfig.java
> +            return new GameSdkConfig(this.maxGames, this.minPlayers, this.gameCreator);
We don't need to sanity check this. Look at how the builder is designed. The stepped builder design specifically ensures that you cannot construct this without setting all these fields. I specifically designed it that way to enforce that requirement at compile time.

2023-07-06 20:00 UTC, BomBardyGamer commented on src/main/java/dev/emortal/minestom/gamesdk/internal/listener/AgonesGameUpdateListener.java
> +    private int gameCount;
I'm going to take this opportunity to discuss that we need to evaluate more of our concurrency practices, and determine where things need to be atomic, where they need to be locked, where they need to be concurrent types, and where they don't need any safety at all. Just making everything concurrent or atomic is a terrible approach to concurrency. This is one of the big things I learned with Krypton, as well as reading the Java Concurrency in Practice book. There are also cases where we could use multiple atomic types, but it wouldn't be atomic, because we are using them separately. There are so many cases where just replacing a type with an atomic one won't work. I didn't make this atomic because I thought it probably wouldn't have enough contention to be worth the overhead, but it's probably important that the game count isn't wrong.

2023-07-06 20:28 UTC, ZakShearman commented on build.gradle.kts
> +    api("dev.emortal.minestom:core:ec7fd44") // should be provided by any user
Will add to just discuss this to the backlog. Comment should still be removed btw or changed to compileOnly IDK

2023-07-06 20:29 UTC, ZakShearman commented on src/main/java/dev/emortal/minestom/gamesdk/internal/GameManager.java
> +            while (this.games.isEmpty()) {
Yes but this doesn't fix that issue. It won't work.

You're checking that games is empty - not whether there is a game for that player. Therefore, if there's already a game on this server this fix simply won't work.

2023-09-02 19:51 UTC, ZakShearman commented
It appears right now that games might not be cleaned up properly so it doesn't get marked as READY. Might just be a blocksumo issue.

2023-09-02 21:48 UTC, ZakShearman requested changes

2023-09-02 22:18 UTC, ZakShearman commented
All happy - just need to test with an implementation (use blocksumo plz)

2023-09-04 22:01 UTC, ZakShearman approved these changes

2023-09-04 22:01 UTC, merged